services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crm_db
    ports:
      - "5432:5432"

  api:
    build: .
    volumes:
      # This maps your local code folder to the /code directory in Docker
      - ./crm_backbone:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/crm_db
      # This ensures Python can see 'app' as a package
      - PYTHONPATH=/code
    depends_on:
      - db